apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: default
spec:
  type: LoadBalancer  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  sessionAffinity: ClientIP # routes users to previously visited pods based on client IP
  selector:
    app: type-a
